// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lex

import "strconv"

const _TokenType_name = "TokenErrorTokenEOFTokenNewLineTokenLeftBracketTokenRightBracketTokenEqualSignTokenSectionTokenKeyTokenValue"

var _TokenType_index = [...]uint8{0, 10, 18, 30, 46, 63, 77, 89, 97, 107}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
