// Code generated by "stringer -type OperationType"; DO NOT EDIT.

package str

import "strconv"

const _OperationType_name = "NoOpCopyReplaceDeleteInsert"

var _OperationType_index = [...]uint8{0, 4, 8, 15, 21, 27}

func (i OperationType) String() string {
	if i < 0 || i >= OperationType(len(_OperationType_index)-1) {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[i]:_OperationType_index[i+1]]
}
