# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
IPS = {
    "master" => "10.13.37.10",
    "proxy1" => "10.13.37.11",
    "proxy2" => "10.13.37.12",
    "app1" => "10.13.37.13",
    "app2" => "10.13.37.14",
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "master" do |master|
    hostname = "master"
    master.vm.network :private_network, ip: IPS[hostname]
    master.vm.provision "shell" do |s|
      s.path = "bin/bootstrap-master.sh"
    end
  end

  config.vm.define "proxy1" do |proxy1|
    hostname = "proxy1"
    proxy1.vm.network :private_network, ip: IPS[hostname]
    proxy1.vm.provision "shell" do |s|
      s.args = [IPS["master"], hostname]
      s.path = "bin/bootstrap-proxy.sh"
    end
  end

  config.vm.define "app1" do |app1|
    hostname = "app1"
    app1.vm.network :private_network, ip: IPS[hostname]
    app1.vm.provision "shell" do |s|
      s.args = [IPS["master"], hostname]
      s.path = "bin/bootstrap-app.sh"
    end
  end

  config.vm.define "proxy2" do |proxy2|
    hostname = "proxy2"
    proxy2.vm.network :private_network, ip: IPS[hostname]
    proxy2.vm.provision "shell" do |s|
      s.args = [IPS["master"], hostname]
      s.path = "bin/bootstrap-proxy.sh"
    end
  end

  config.vm.define "app2" do |app2|
    hostname = "app2"
    app2.vm.network :private_network, ip: IPS[hostname]
    app2.vm.provision "shell" do |s|
      s.args = [IPS["master"], hostname]
      s.path = "bin/bootstrap-app.sh"
    end
  end
end
